name: Deploy to Cloudflare

on:
  repository_dispatch:
    types: [cms-content-updated]
  workflow_dispatch:
    inputs:
      site:
        description: 'Which site to deploy'
        required: false
        default: 'both'
        type: choice
        options:
          - both
          - molly
          - micah

jobs:
  determine-sites:
    runs-on: ubuntu-latest
    outputs:
      sites: ${{ steps.sites.outputs.sites }}
    steps:
      - name: Determine sites to deploy
        id: sites
        run: |
          # Check if this was triggered by repository_dispatch
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            SITE_FILTER="${{ github.event.client_payload.site || 'both' }}"
          else
            SITE_FILTER="${{ github.event.inputs.site || 'both' }}"
          fi
          
          case $SITE_FILTER in
            "molly"|"mollyferguson"|"mollyferguson.info")
              echo 'sites=["molly"]' >> $GITHUB_OUTPUT
              ;;
            "micah"|"micah-ferguson")
              echo 'sites=["micah"]' >> $GITHUB_OUTPUT
              ;;
            *)
              echo 'sites=["molly","micah"]' >> $GITHUB_OUTPUT
              ;;
          esac

  deploy:
    needs: determine-sites
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        site: ${{ fromJson(needs.determine-sites.outputs.sites) }}
        include:
          - site: molly
            app_name: mollyferguson.info
            endpoint: https://us-east-1-shared-usea1-02.cdn.hygraph.com/content/cm048oo3l01gz07wf7rrq84lg/master
            build_command: build:molly
            deploy_command: deploy:molly
          - site: micah
            app_name: micah-ferguson
            endpoint: https://us-west-2.cdn.hygraph.com/content/cm4ah46tx01ol07lnfafy43gg/master
            build_command: build:micah
            deploy_command: deploy:micah
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      NPM_GH_TOKEN: ${{ secrets.NPM_GH_TOKEN }}
      ASTRO_HYGRAPH_ENDPOINT: ${{ matrix.endpoint }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build ${{ matrix.app_name }}
      run: npm run ${{ matrix.build_command }}

    - name: Deploy ${{ matrix.app_name }}
      run: npm run ${{ matrix.deploy_command }}

    - name: Report deployment status
      run: |
        echo "🚀 Deployment of ${{ matrix.app_name }} completed successfully!"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Site: ${{ matrix.site }}" 