name: Site Deploy

on:
  repository_dispatch:
    types: [molly, micah, caleb]
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to deploy'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - molly
          - micah
          - caleb

jobs:
  deploy-molly:
    if: |
      github.event.action == 'molly' || 
      github.event.inputs.site == 'molly' || 
      github.event.inputs.site == 'all'
    runs-on: ubuntu-latest
    environment: production
    
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      NPM_GH_TOKEN: ${{ secrets.NPM_GH_TOKEN }}
      ASTRO_HYGRAPH_ENDPOINT: https://us-east-1-shared-usea1-02.cdn.hygraph.com/content/cm048oo3l01gz07wf7rrq84lg/master

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build mollyferguson.info
      run: npm run build:molly

    - name: Deploy mollyferguson.info
      run: npm run deploy:molly

    - name: Report deployment status
      run: |
        echo "🚀 Deployment of mollyferguson.info completed successfully!"
        echo "Triggered by: ${{ github.event_name }}"

  deploy-micah:
    if: |
      github.event.action == 'micah' || 
      github.event.inputs.site == 'micah' || 
      github.event.inputs.site == 'all'
    runs-on: ubuntu-latest
    environment: production
    
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      NPM_GH_TOKEN: ${{ secrets.NPM_GH_TOKEN }}
      ASTRO_HYGRAPH_ENDPOINT: https://us-west-2.cdn.hygraph.com/content/cm4ah46tx01ol07lnfafy43gg/master

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build micah-ferguson
      run: npm run build:micah

    - name: Deploy micah-ferguson
      run: npm run deploy:micah

    - name: Report deployment status
      run: |
        echo "🚀 Deployment of micah-ferguson completed successfully!"
        echo "Triggered by: ${{ github.event_name }}" 

  deploy-caleb:
    if: |
      github.event.action == 'caleb' || 
      github.event.inputs.site == 'caleb' || 
      github.event.inputs.site == 'all'
    runs-on: ubuntu-latest
    environment: production
    
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      NPM_GH_TOKEN: ${{ secrets.NPM_GH_TOKEN }}
      ASTRO_HYGRAPH_ENDPOINT: https://us-west-2.cdn.hygraph.com/content/cmd3k49mt1tr907mybbem3cyg/master

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build caleb
      run: npm run build:caleb

    - name: Deploy caleb
      run: npm run deploy:caleb

    - name: Report deployment status
      run: |
        echo "🚀 Deployment of caleb completed successfully!"
        echo "Triggered by: ${{ github.event_name }}" 